using UnityEngine;

namespace Oheangbu.App.World.UI
{
    /// <summary>#304 HUD area tokens that the foundation style (UiStyle304SO) does not carry yet: the REFERENCE_BOARD deltas
    /// applied to the HUD (D02 lock-on idle stage, D07 thinner meters, D08 centred prompt, D13 bearing pictograms, D23 bearing
    /// auto behaviour, D35 pin X) and the HUD sprites generated by Art/UI304/gen/hud_assets.py (Textures/hud/). Field initializers
    /// ARE the design values. The asset lives at Resources/UI304/hud/HudTokens304.asset (made by the editor command
    /// Oheangbu.EditorTools.WorldMacro.HudSetup304 Execute("hud304-setup")); without it the code defaults are used and the
    /// sprite slots fall back (enso keeps its gap, pictograms use CompactUiProfileSO icons, the spine uses stroke_spine + bleed).
    /// Not a singleton: one immutable data asset, loaded once per Play session.</summary>
    [CreateAssetMenu(menuName = "Oheangbu/UI/UI304 HUD Tokens", fileName = "HudTokens304")]
    public sealed class HudTokens304 : ScriptableObject
    {
        public const string ResourcePath = "UI304/hud/HudTokens304";

        [Header("D07 meters (length kept: HP 500, 먹 420 from UiStyle304SO.Meter)")]
        public float HpHeight = 30;
        public float InkHeight = 21;
        [Tooltip("gap between the HP stroke bottom and the ink stroke top (mockup 42 -> 56 = 14)")] public float MeterGap = 14;
        [Tooltip("received-ink flash (NotifyInkGained): colour alpha and life")] public float ReceivedAlpha = .85f, ReceivedSeconds = .45f;

        [Header("D02 lock-on: idle 52 px α.45, full size (LockOn.EnsoSize) once groggy starts")]
        public float IdleEnsoSize = 52;
        public float IdleAlpha = .45f;
        [Tooltip("parry pulse (PulseReticle) scale amplitude; 0 = off")] public float PulseScale = .12f;

        [Header("D08 prompt: content centred on x960, underlay grows both ways, tail slice stays right")]
        public float PromptCentreX = 960;
        [Tooltip("underlay left edge before the key (mockup 800 - 736)")] public float PromptKeyLead = 64;
        [Tooltip("key right edge to verb (mockup 860 - 840)")] public float PromptKeyGap = 20;
        [Tooltip("longer verb phrases wrap inside this width")] public float PromptMaxLabelWidth = 1100;
        [Tooltip("max underlay height (WetS class band)")] public float PromptMaxHeight = 124;

        [Header("D23 bearing line auto mode (Settings.ShowMinimap = on / off)")]
        [Tooltip("full alpha after an arrival card or a respawn")] public float EmphasisSeconds = 4;
        public float MovingAlpha = .5f;
        [Tooltip("horizontal body speed (m/s) that counts as moving")] public float MovingSpeed = .6f;
        public int FadeMs = 200;
        [Tooltip("labels fade out over this many degrees before the ±90° ends")] public float LabelEdgeFadeDeg = 15;
        [Tooltip("rest / place pictograms beyond this distance are left off the line (objective, coin, pin always show)")]
        public float PlaceRangeMeters = 400;
        public int MaxMarkers = 16;
        [Tooltip("marker refresh interval (IMapMarkerSource304.CollectMarkers)")] public float MarkerRefreshSeconds = .25f;
        [Tooltip("D35 pin X: box and stroke thickness (stroke_short, ink with a paper halo)")] public float PinSize = 24, PinStroke = 7;
        [Tooltip("D13 place pictogram by label: any of these -> cave arch, then mountain peaks, else the stele")]
        public string[] CaveWords = { "굴", "광", "혈" };
        public string[] MountainWords = { "산", "봉", "령", "고개" };

        [Header("low-HP ink edges (fitted to the canvas)")]
        public float EdgeTopBottom = 90, EdgeSide = 70, EdgeSideAlpha = .78f;
        [Tooltip("share of Skin.MaximumDangerAlpha shown as soon as HP drops below Skin.DangerBeginsAtHp (0 = the old linear ramp " +
                 "from zero, which left the edge invisible at 28% HP); it then grows to the full value at HP 0")]
        [Range(0f, 1f)] public float DangerOnset = .6f;
        [Tooltip("HP band below the threshold over which the onset share eases in (no pop at the threshold)")]
        public float DangerOnsetBand = .05f;

        [Header("QA1/QA2: Linear colour space (the FINAL mockups composite in sRGB)")]
        [Tooltip("dark-ink layer alpha in a Linear project: a' = 1 - (1 - a)^g, for HUD graphics on a material WITHOUT the foundation " +
                 "remap (InkAlphaFor passes remapping materials through). 1 = off (the HUD's own ink layers are all on UI/InkReveal / " +
                 "UI/InkMeter now, which remap with _LinearInkGamma themselves)")]
        public float LinearInkGamma = 1f;
        [Tooltip("QA2: the meters' paper value rim (α.72) as a rim only (true) or as the mockup's paper plate under the whole value " +
                 "(false). QA1 set true to stop linear blending from greying the value; with the UI/InkMeter remap the plate is what " +
                 "brings the mockup's brush streaks and HP colour back (ink value ~63 vs mockup 64, rim only ~29)")]
        public bool MeterValueRimEdgeOnly = false;
        [Tooltip("QA2: paper layers over the WORLD (meter ghost edge α.3, value rim α.72). The foundation remap a' = a^g is exact for " +
                 "paper over ink only; over the mid-grey world it erased the rims (ghost edge .3 -> .07). The HUD pre-scales their " +
                 "vertex alpha to a^(k / g) so they land at a^k; k 1.3 matches hud.png / states.png on grounds 40..200. " +
                 "k >= the shader gamma (2.2) = leave the shader remap alone")]
        public float PaperOverWorldExponent = 1.3f;
        [Tooltip("QA2: meter VALUE alpha while UI/InkMeter remaps ink alpha (1 = off). The remap is exact over white; over the paper " +
                 "value plate it overshoots (ink value 52 vs mockup 64, HP value flat): .92 lands at 63 and keeps the streaks")]
        [Range(.5f, 1f)] public float MeterValueAlpha = .92f;
        [Tooltip("QA2: the cinnabar HP lag (lost share, α.34) undoes the dark remap (1-(1-a)^g made it α.60, nearly the value colour); " +
                 "the lag is then α.34 in linear, close to the mockup's (120,85,75)")]
        public bool LagUndoRemap = true;

        [Header("arrival card")]
        [Tooltip("horizontal fallback name: gap below the spine")] public float ArrivalFallbackGap = 12;

        [Header("sprites (Textures/hud, hud304-setup)")]
        public Sprite EnsoClosed;
        public Sprite EnsoClosedRim;
        [Tooltip("stroke_spine rotated 90° CCW: the arrival card draws it top -> bottom with the Wipe reveal")] public Sprite SpineAcross;
        public Sprite PictoRest, PictoRestRim, PictoCave, PictoCaveRim, PictoMountain, PictoMountainRim, PictoPlace, PictoPlaceRim, PictoCoin, PictoCoinRim;

        // ------------------------------------------------------------------ load (Resources path, one read per Play session)
        static HudTokens304 loaded, fallback;
        static bool tried;
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
        static void ResetStatics() { loaded = null; fallback = null; tried = false; }

        /// <summary>The asset at Resources/UI304/hud/HudTokens304, or an asset-less default instance (design values, no sprites).</summary>
        public static HudTokens304 Load()
        {
            if (loaded != null) return loaded;
            if (!tried) { tried = true; loaded = Resources.Load<HudTokens304>(ResourcePath); if (loaded != null) return loaded; }
            if (fallback == null) { fallback = CreateInstance<HudTokens304>(); fallback.name = "HudTokens304 (defaults)"; fallback.hideFlags = HideFlags.DontSave; }
            return fallback;
        }

        public static bool IsDefault(HudTokens304 t) => t == null || t == fallback;

        /// <summary>QA1: alpha for a near-black ink layer (먹 #141413 / 먹장막 #0F0F0E) drawn over the world. The mockups composite in
        /// sRGB, Unity (Linear project) in linear light, where a translucent dark layer looks far lighter (measured: ghost α.27
        /// reads as α~.12, ink value on its paper rim as mid grey). For black ink the sRGB result (1 - a)·dst is reproduced in
        /// linear by a' = 1 - (1 - a)^2.2. Gamma projects (or LinearInkGamma 1) return `a` unchanged.</summary>
        public float InkAlpha(float a)
        {
            a = Mathf.Clamp01(a);
            if (LinearInkGamma <= 1f || QualitySettings.activeColorSpace != ColorSpace.Linear) return a;
            return 1f - Mathf.Pow(1f - a, LinearInkGamma);
        }

        /// <summary>QA2: InkAlpha only for a material that does NOT remap (plain UI/Default, fallback style); a foundation material
        /// (UI/InkReveal, UI/InkMeter with _LinearInkGamma &gt; 1) already compensates, so `a` is returned as is (no double remap).</summary>
        public float InkAlphaFor(Material material, float a) => ShaderInkGamma(material) > 1.0001f ? Mathf.Clamp01(a) : InkAlpha(a);

        /// <summary>QA2: vertex alpha for a PAPER layer drawn over the world on a remapping material: the shader's light remap
        /// (a^g, exact over ink) is pre-scaled to land at a^PaperOverWorldExponent. Materials without the remap return `a`.</summary>
        public float PaperAlpha(Material material, float a)
        {
            a = Mathf.Clamp01(a);
            float g = ShaderPaperGamma(material);
            if (g <= 1.0001f || PaperOverWorldExponent <= 0f || PaperOverWorldExponent >= g) return a;
            return Mathf.Pow(a, PaperOverWorldExponent / g);
        }

        /// <summary>QA2: vertex alpha that undoes the shader's dark remap (a' = 1-(1-a)^g) for a coloured translucent layer (the
        /// cinnabar lag), so it composites at `a` in linear light. Materials without the remap return `a`.</summary>
        public float UndoInkRemap(Material material, float a)
        {
            a = Mathf.Clamp01(a);
            float g = ShaderInkGamma(material);
            return g > 1.0001f ? 1f - Mathf.Pow(1f - a, 1f / g) : a;
        }

        /// <summary>QA2: the linear-space ink gamma a foundation material applies (UI/InkReveal / UI/InkMeter _LinearInkGamma);
        /// 1 for null, a material without the property, or a Gamma project (the shaders skip the remap there).</summary>
        public static float ShaderInkGamma(Material material)
        {
            if (material == null || QualitySettings.activeColorSpace != ColorSpace.Linear || !material.HasProperty(InkGammaId)) return 1f;
            return Mathf.Max(1f, material.GetFloat(InkGammaId));
        }

        /// <summary>QA2: the gamma of the shader's light (paper) remap: _LinearPaperGamma when the foundation adds one, else the
        /// shared _LinearInkGamma (today's shaders use one gamma for both branches).</summary>
        public static float ShaderPaperGamma(Material material)
        {
            if (material != null && QualitySettings.activeColorSpace == ColorSpace.Linear && material.HasProperty(PaperGammaId))
                return Mathf.Max(1f, material.GetFloat(PaperGammaId));
            return ShaderInkGamma(material);
        }

        static readonly int InkGammaId = Shader.PropertyToID("_LinearInkGamma");
        static readonly int PaperGammaId = Shader.PropertyToID("_LinearPaperGamma");

        /// <summary>Low-HP edge alpha before InkAlpha: 0 above `beginsAt`; below it the onset share eases in over DangerOnsetBand,
        /// then grows linearly to `max` at HP 0.</summary>
        public float DangerAlpha(float hp01, float beginsAt, float max)
        {
            if (hp01 >= beginsAt || max <= 0f) return 0f;
            float onset = DangerOnsetBand > 0f ? Mathf.InverseLerp(beginsAt, beginsAt - DangerOnsetBand, hp01) : 1f;
            float t = Mathf.InverseLerp(beginsAt, 0f, hp01);
            return max * onset * Mathf.Lerp(DangerOnset, 1f, t);
        }

        /// <summary>D13 pictogram pair (core, rim) for a marker kind; place kinds are chosen from the label words.</summary>
        public void Pictogram(MapMarkerKind304 kind, string label, out Sprite core, out Sprite rim)
        {
            switch (kind)
            {
                case MapMarkerKind304.Rest: core = PictoRest; rim = PictoRestRim; return;
                case MapMarkerKind304.Coin: core = PictoCoin; rim = PictoCoinRim; return;
                case MapMarkerKind304.Place:
                    if (Has(label, CaveWords)) { core = PictoCave; rim = PictoCaveRim; return; }
                    if (Has(label, MountainWords)) { core = PictoMountain; rim = PictoMountainRim; return; }
                    core = PictoPlace; rim = PictoPlaceRim; return;
                default: core = null; rim = null; return;
            }
        }

        /// <summary>#304 integration: D13 pictogram from the map's baked place kind (WorldMapPresenter.TryDetailKind304):
        /// mountain = peaks, gate = arch, rest / checkpoint = roof, settlement = the map's own village pictogram (MapStyle304SO,
        /// no rim sprite: the bearing line draws its 1.12x paper copy); a plain place keeps the label-word rule.</summary>
        public void Pictogram(WorldMapMarkerKind detail, string label, out Sprite core, out Sprite rim)
        {
            switch (detail)
            {
                case WorldMapMarkerKind.Mountain: core = PictoMountain; rim = PictoMountainRim; return;
                case WorldMapMarkerKind.Gate: core = PictoCave; rim = PictoCaveRim; return;
                case WorldMapMarkerKind.Rest: case WorldMapMarkerKind.Checkpoint: core = PictoRest; rim = PictoRestRim; return;
                case WorldMapMarkerKind.Settlement:
                    var map = MapStyle304SO.Resolve();
                    if (map != null && map.PictVillage != null) { core = map.PictVillage; rim = null; return; }
                    Pictogram(MapMarkerKind304.Place, label, out core, out rim); return;
                default: Pictogram(MapMarkerKind304.Place, label, out core, out rim); return;
            }
        }

        /// <summary>Which place family a label reads as: 0 stele, 1 cave, 2 mountain (fallback icon choice).</summary>
        public int PlaceFamily(string label) => Has(label, CaveWords) ? 1 : Has(label, MountainWords) ? 2 : 0;

        static bool Has(string label, string[] words)
        {
            if (string.IsNullOrEmpty(label) || words == null) return false;
            foreach (var w in words) if (!string.IsNullOrEmpty(w) && label.Contains(w)) return true;
            return false;
        }
    }
}
