using System;
using System.Collections.Generic;
using UnityEngine;

namespace Oheangbu.App.World.UI
{
    /// <summary>들은 목적 권역 mark (REFERENCE_BOARD D47 A/B): the open brush circle (enso, same grammar as the lock-on) or the
    /// dashed ring of map.png.</summary>
    public enum MapObjectiveMark304 { OpenBrush = 0, DashedRing = 1 }

    /// <summary>Legend symbols (DESIGN §5.13, 7 rows).</summary>
    public enum MapLegendSymbol304 { Player = 0, Rest = 1, Place = 2, Coin = 3, Pin = 4, Objective = 5, Unwalked = 6 }

    [Serializable]
    public sealed class MapLegendRow304
    {
        public MapLegendSymbol304 Symbol;
        public string Name;
        [Tooltip("plain-language meaning (Meta20, one line at 410 px; no orphan word on a second line)")] public string Meaning;
        public MapLegendRow304() { }
        public MapLegendRow304(MapLegendSymbol304 symbol, string name, string meaning) { Symbol = symbol; Name = name; Meaning = meaning; }
    }

    /// <summary>What the places list and the detail card say about one kind of place.</summary>
    [Serializable]
    public sealed class MapKindText304
    {
        public MapMarkerKind304 Kind;
        [Tooltip("kind meta on the list row and the detail card (쉼터 · 장소 · 의뢰 · 남긴 통보 · 내 표식)")] public string Name;
        [Tooltip("detail card body when the place has no text of its own")] public string Description;
        public MapKindText304() { }
        public MapKindText304(MapMarkerKind304 kind, string name, string description) { Kind = kind; Name = name; Description = description; }
    }

    /// <summary>#304 map screen data (WorldMapPresenter): the map area's own sprites (Textures/map, generated by
    /// Art/UI304/gen/map_assets.py) and the tunables that are not layout. Page layout stays in code as mockup px (map.png),
    /// like every other #304 page. The asset lives at Resources/UI304/map/MapStyle304 (created and wired by the editor
    /// command MapSetup304 "map304-setup"); without it the presenter uses the code defaults below and falls back to the
    /// UIIcons pictures / foundation sprites, so nothing disappears.</summary>
    [CreateAssetMenu(menuName = "Oheangbu/UI/UI304 Map Style", fileName = "MapStyle304")]
    public sealed class MapStyle304SO : ScriptableObject
    {
        public const string ResourcePath = "UI304/map/MapStyle304";

        [Header("sprites (Textures/map)")]
        [Tooltip("D13 flat pictograms for 30~32 px (places list, HUD bearing line). 44 px and more keep the UIIcons pictures")]
        public Sprite PictRest;
        public Sprite PictCave, PictMountain, PictGate, PictVillage;
        [Tooltip("D04 조선통보 symbol (남긴 통보, D14)")] public Sprite Coin;
        [Tooltip("D14 variant ring: same symbol + outer ink ring (the rest where you wake)")] public Sprite VariantRing;
        [Tooltip("D11 제첨 테 for the vertical title slip (sliced 20)")] public Sprite SlipFrame;

        [Header("view")]
        [Tooltip("현재 위치 view on an illustrated map: screen px per illustration texel at page scale 1 (DESIGN §7.6: 1.5배 = 493 of 1024 px)")]
        public float CurrentViewTexelScale = 1.5f;
        [Tooltip("현재 위치 view width (world metres) on a painted-relief map without a readable illustration texture (the pre-#304 view)")]
        public float PaintedCurrentMetres = 1100f;
        [Tooltip("현재 위치 view width (world metres) without an illustration")] public float PlainCurrentMetres = 640f;
        [Tooltip("현재 위치 view width (world metres) inside a cave / interior zone")] public float InteriorCurrentMetres = 150f;
        [Tooltip("place labels show while the view is narrower than this fraction of the world width")] public float LabelMaxViewWidth = .62f;

        [Header("paper")]
        [Tooltip("걷지 않은 땅: sheet veil over undiscovered cells of the illustration (map_fog of the mockup is .84)"), Range(0f, 1f)]
        public float UnknownVeil = .84f;
        [Tooltip("걷지 않은 땅 = 안개 덮인 그림 (#304 QA): monochrome share of the walked shading the fog keeps (0 = the flat sheet veil)"), Range(0f, 1f)]
        public float UnknownShade = .15f;
        [Tooltip("걷지 않은 땅: ink gain of the illustration's local relief under the fog (0 = none). Keeps a low-contrast painted relief readable")]
        public float UnknownRelief = 2.5f;
        [Tooltip("걷지 않은 땅: radius of the relief's local average, in illustration texels")] public float UnknownReliefTexels = 8f;
        [Tooltip("walked-land edge: rounded and wobbling instead of the square 32 m cell steps (inward only, never reveals an unknown cell)")]
        public bool FogSoftEdge = true;
        [Tooltip("walked-land edge wobble")] public float FogEdgeNoise = .22f;
        [Tooltip("realm names keep this margin (page px) from the print edge and from the title slip and 북 on the paper")]
        public float RegionLabelMarginPx = 10f;
        [Tooltip("painted relief (the compact world's olive hillshade, cyan water, pink zone patches) printed as a monochrome ink wash on the sheet (#304 QA2; DESIGN §2.5 bans the old minimap green and a second accent). 0 = the coloured relief"), Range(0f, 1f)]
        public float PaintedInkWash = 1f;
        [Tooltip("ink wash: relief luminance (sRGB) at and above which the sheet stays bare")] public float PaintedInkLight = .55f;
        [Tooltip("ink wash: relief luminance (sRGB) at and below which the ink is full")] public float PaintedInkDark = .36f;
        [Tooltip("ink wash: the fullest ink, as the share of the sheet it takes away (sRGB multiply)"), Range(0f, 1f)] public float PaintedInkMax = .66f;
        [Tooltip("ink wash: gain of the zone-paint neutraliser (magenta patches, red and blue above green, print no ink); 0 = off")]
        public float PaintedZoneNeutral = 12f;

        [Header("marks (px at page scale 1)")]
        public float PlayerSize = 48f;
        public float RestSize = 34f, PlaceSize = 30f, CoinSize = 22f, PinSize = 30f;
        [Tooltip("D14 variant ring diameter / symbol size")] public float VariantRingScale = 1.5f;
        [Tooltip("objective ring minimum diameter (the world radius sets it otherwise)")] public float ObjectiveMinSize = 64f;
        public MapObjectiveMark304 Objective = MapObjectiveMark304.OpenBrush;
        [Tooltip("the checkpoint counts as that rest when within this distance (m)")] public float CheckpointSnapMetres = 14f;

        [Header("대동여지도 layer (D15) on the printed window")]
        [Tooltip("roads as straight thin ink lines with right-angle distance ticks, rivers as uncoloured double lines, realm borders dotted")]
        public bool Daedong = true;
        [Tooltip("Douglas-Peucker tolerance that straightens road polylines (m)")] public float RoadStraightenMetres = 12f;
        [Tooltip("road stroke width (display px)")] public float RoadWidthPx = 2.2f;
        [Tooltip("one tick = this many metres of road (PROPOSED distance unit, LDB to confirm)")] public float RoadTickMetres = 200f;
        [Tooltip("ticks are left out while their spacing is under this many display px (the unit never changes)")] public float RoadTickMinPx = 16f;
        public float RoadTickLengthPx = 7f, RoadTickWidthPx = 1.3f;
        [Tooltip("rivers wider than this (display px) draw as a double line, narrower as one line")] public float RiverDoubleMinPx = 3.2f;
        [Tooltip("...and only while zoomed in closer than this many metres per display px (the whole-world view keeps single lines)")] public float RiverDoubleMaxMetresPerPx = 8f;
        public float RiverRimPx = 1.2f, RiverSinglePx = 1.6f;
        public float BorderDotPx = 2.2f, BorderDotGapPx = 9f;

        [Header("text (content, editable here)")]
        public List<MapLegendRow304> Legend = DefaultLegend();
        public List<MapKindText304> Kinds = DefaultKinds();
        [Tooltip("places list rows visible before it scrolls")] public int ListVisibleRows = 5;

        public MapKindText304 Kind(MapMarkerKind304 kind)
        {
            if (Kinds != null) foreach (var k in Kinds) if (k != null && k.Kind == kind) return k;
            foreach (var k in DefaultKinds()) if (k.Kind == kind) return k;
            return new MapKindText304(kind, "", "");
        }

        public static List<MapLegendRow304> DefaultLegend() => new List<MapLegendRow304>
        {
            new MapLegendRow304(MapLegendSymbol304.Player, "현재 위치", "지금 선 자리와 바라보는 쪽"),
            new MapLegendRow304(MapLegendSymbol304.Rest, "쉼터", "쉬면 체력과 먹이 찬다. 고리 두른 곳에서 깬다"),
            new MapLegendRow304(MapLegendSymbol304.Place, "발견한 장소", "다녀가서 이름을 안 곳. 그림이 곳의 생김이다"),
            new MapLegendRow304(MapLegendSymbol304.Coin, "남긴 통보", "쓰러진 자리에 떨어뜨린 조선통보"),
            new MapLegendRow304(MapLegendSymbol304.Pin, "내 표식", "지도에 직접 찍어 둔 자리"),
            new MapLegendRow304(MapLegendSymbol304.Objective, "들은 목적 권역", "의뢰에서 들은 곳 일대"),
            new MapLegendRow304(MapLegendSymbol304.Unwalked, "걷지 않은 땅", "걸어 본 땅만 먹이 선명하다"),
        };

        public static List<MapKindText304> DefaultKinds() => new List<MapKindText304>
        {
            new MapKindText304(MapMarkerKind304.Rest, "쉼터", "쉬면 체력과 먹이 차고, 쓰러지면 마지막으로 쉰 쉼터에서 깬다."),
            new MapKindText304(MapMarkerKind304.Place, "장소", "다녀가서 이름을 안 곳이다."),
            new MapKindText304(MapMarkerKind304.Objective, "의뢰", "의뢰에서 들은 곳 일대다."),
            new MapKindText304(MapMarkerKind304.Coin, "남긴 통보", "쓰러진 자리에 떨어뜨린 조선통보다. 가서 주우면 되찾는다."),
            new MapKindText304(MapMarkerKind304.Pin, "내 표식", "지도에 직접 찍어 둔 자리다."),
        };

        // ------------------------------------------------------------------ lookup (not a singleton: a cached asset reference)
        static MapStyle304SO cached, fallback;
        static bool looked;
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
        static void ResetStatics() { cached = null; fallback = null; looked = false; }

        /// <summary>The asset at Resources/UI304/map/MapStyle304, else an in-memory instance with the code defaults
        /// (no sprites: callers fall back to UIIcons pictures and foundation sprites).</summary>
        public static MapStyle304SO Resolve()
        {
            if (cached != null) return cached;
            if (!looked) { looked = true; cached = Resources.Load<MapStyle304SO>(ResourcePath); if (cached != null) return cached; }
            if (fallback == null)
            {
                fallback = CreateInstance<MapStyle304SO>();
                fallback.name = "MapStyle304 (code defaults)"; fallback.hideFlags = HideFlags.DontSave;
            }
            return fallback;
        }

        public static bool IsFallback(MapStyle304SO style) => style == null || style == fallback;

        /// <summary>D13 pictogram for an IMapMarkerSource304 entry (the HUD bearing line's 32 px place marks): Rest = roof,
        /// Place = arch, Coin = 조선통보. Pin and Objective return null (the bearing line draws its X / 목적 방점).</summary>
        public Sprite Pictogram(MapMarkerKind304 kind)
        {
            switch (kind)
            {
                case MapMarkerKind304.Rest: return PictRest;
                case MapMarkerKind304.Place: return PictCave;
                case MapMarkerKind304.Coin: return Coin;
                default: return null;
            }
        }

        /// <summary>D13 pictogram for a marker kind (30~32 px). null when the asset is missing.</summary>
        public Sprite Pictogram(WorldMapMarkerKind kind)
        {
            switch (kind)
            {
                case WorldMapMarkerKind.Rest: case WorldMapMarkerKind.Checkpoint: return PictRest;
                case WorldMapMarkerKind.Mountain: return PictMountain;
                case WorldMapMarkerKind.Gate: return PictGate != null ? PictGate : PictCave;
                case WorldMapMarkerKind.Settlement: return PictVillage != null ? PictVillage : PictRest;
                case WorldMapMarkerKind.Drop: return Coin;
                default: return PictCave;
            }
        }
    }
}
