# #307 (2026-10-01): KoreanInkGround296 GPU cost switches, applied after the #296 transform so a rebuild keeps them.
# _Perf307Ground = A/B cost split flags (0 = off); _TriplanarSkip307 = triplanar rock projections at or below this weight are not
# sampled (ground material 554e7538: .004, near-identical, GPU -1.4..-3.3 ms at 2560x1440). Both default to 0 = the #296 arithmetic.
PAIRS = {
    'KoreanInkGround296.shader': [
        ('        _StrataStrength276("Terrain material rules (candidate only)",Range(0,1))=0\n',
         '        _StrataStrength276("Terrain material rules (candidate only)",Range(0,1))=0\n        // #307 GPU cost split only (0 = the shipped shader, bit-identical): 1 prepass normal = mesh normal, 2 forward rule normal = mesh\n        // normal, 4 rule colour without rock/cavity triplanar, 8 rule colour without the near realm floor\n        _Perf307Ground("#307 ground cost split flags (0 = off)",Float)=0\n'),
        ('        float _RealmStrength293; float _StrataStrength276;float4 _StrataRange276;',
         '        float _RealmStrength293; float _StrataStrength276;float4 _StrataRange276;float _Perf307Ground;'),
        ('                    float3 rn=RuleNormal276(p,n,masks,cameraDistance);\n                    Light light=GetMainLight(TransformWorldToShadowCoord(p));',
         '                    float3 rn=((uint)_Perf307Ground&2u)!=0u?n:RuleNormal276(p,n,masks,cameraDistance);\n                    Light light=GetMainLight(TransformWorldToShadowCoord(p));'),
        ('                if(weight>0)\n                {\n                    float2 uv=(i.world.xz-_GroundPathRect.xy)*_GroundPathRect.zw;',
         '                if(weight>0&&((uint)_Perf307Ground&1u)==0u)\n                {\n                    float2 uv=(i.world.xz-_GroundPathRect.xy)*_GroundPathRect.zw;'),
        ('        _Perf307Ground("#307 ground cost split flags (0 = off)",Float)=0\n',
         '        _Perf307Ground("#307 ground cost split flags (0 = off)",Float)=0\n        // #307: triplanar rock projections whose blend weight is at most this are not sampled (their share of the result is at most\n        // this fraction). 0 = every projection sampled (the original arithmetic).\n        _TriplanarSkip307("#307 triplanar projection skip weight",Range(0,.02))=0\n'),
        ('float _Perf307Ground;',
         'float _Perf307Ground;float _TriplanarSkip307;'),
    ],
    'KoreanSurface296.hlsl': [
        ('    if(distanceWS<750)\n    {',
         '    if(distanceWS<750&&((uint)_Perf307Ground&4u)==0u)\n    {'),
        ('        if(nearFloor>.001)\n        {\n            float3 f=0;float used=0;',
         '        if(nearFloor>.001&&((uint)_Perf307Ground&8u)==0u)\n        {\n            float3 f=0;float used=0;'),
        ('    SurfaceFrame296 fx=SurfaceFrameGrad296(q.zy,qdx.zy,qdy.zy,19u,0);\n    SurfaceFrame296 fy=SurfaceFrameGrad296(q.xz,qdx.xz,qdy.xz,19u,0);\n    SurfaceFrame296 fz=SurfaceFrameGrad296(q.xy,qdx.xy,qdy.xy,19u,0);\n    float3 x=SurfaceNormal296(TEXTURE2D_ARGS(_StrataFractureNormal276,sampler_Surface296_linear_repeat_aniso8),fx,1.25*detail);\n    float3 y=SurfaceNormal296(TEXTURE2D_ARGS(_StrataFractureNormal276,sampler_Surface296_linear_repeat_aniso8),fy,1.25*detail);\n    float3 z=SurfaceNormal296(TEXTURE2D_ARGS(_StrataFractureNormal276,sampler_Surface296_linear_repeat_aniso8),fz,1.25*detail);\n    float3 perturb=float3(0,x.y,x.x)*w.x+float3(y.x,0,y.y)*w.y+float3(z.x,z.y,0)*w.z;\n    // The fine rock normal and the rock colour share the same projection and seed.\n    fx=SurfaceFrameGrad296(q.zy,qdx.zy,qdy.zy,17u,0);\n    fy=SurfaceFrameGrad296(q.xz,qdx.xz,qdy.xz,17u,0);\n    fz=SurfaceFrameGrad296(q.xy,qdx.xy,qdy.xy,17u,0);\n    x=SurfaceNormal296(TEXTURE2D_ARGS(_RockNormal,sampler_Surface296_linear_repeat_aniso8),fx,.55*detail);\n    y=SurfaceNormal296(TEXTURE2D_ARGS(_RockNormal,sampler_Surface296_linear_repeat_aniso8),fy,.55*detail);\n    z=SurfaceNormal296(TEXTURE2D_ARGS(_RockNormal,sampler_Surface296_linear_repeat_aniso8),fz,.55*detail);\n    perturb+=float3(0,x.y,x.x)*w.x+float3(y.x,0,y.y)*w.y+float3(z.x,z.y,0)*w.z;',
         '    float3 perturb=0;\n    // #307: a projection at or below _TriplanarSkip307 is not sampled (0 keeps every projection)\n    [branch] if(w.x>_TriplanarSkip307){float3 x=SurfaceNormal296(TEXTURE2D_ARGS(_StrataFractureNormal276,sampler_Surface296_linear_repeat_aniso8),SurfaceFrameGrad296(q.zy,qdx.zy,qdy.zy,19u,0),1.25*detail);perturb+=float3(0,x.y,x.x)*w.x;}\n    [branch] if(w.y>_TriplanarSkip307){float3 y=SurfaceNormal296(TEXTURE2D_ARGS(_StrataFractureNormal276,sampler_Surface296_linear_repeat_aniso8),SurfaceFrameGrad296(q.xz,qdx.xz,qdy.xz,19u,0),1.25*detail);perturb+=float3(y.x,0,y.y)*w.y;}\n    [branch] if(w.z>_TriplanarSkip307){float3 z=SurfaceNormal296(TEXTURE2D_ARGS(_StrataFractureNormal276,sampler_Surface296_linear_repeat_aniso8),SurfaceFrameGrad296(q.xy,qdx.xy,qdy.xy,19u,0),1.25*detail);perturb+=float3(z.x,z.y,0)*w.z;}\n    // The fine rock normal and the rock colour share the same projection and seed.\n    [branch] if(w.x>_TriplanarSkip307){float3 x=SurfaceNormal296(TEXTURE2D_ARGS(_RockNormal,sampler_Surface296_linear_repeat_aniso8),SurfaceFrameGrad296(q.zy,qdx.zy,qdy.zy,17u,0),.55*detail);perturb+=float3(0,x.y,x.x)*w.x;}\n    [branch] if(w.y>_TriplanarSkip307){float3 y=SurfaceNormal296(TEXTURE2D_ARGS(_RockNormal,sampler_Surface296_linear_repeat_aniso8),SurfaceFrameGrad296(q.xz,qdx.xz,qdy.xz,17u,0),.55*detail);perturb+=float3(y.x,0,y.y)*w.y;}\n    [branch] if(w.z>_TriplanarSkip307){float3 z=SurfaceNormal296(TEXTURE2D_ARGS(_RockNormal,sampler_Surface296_linear_repeat_aniso8),SurfaceFrameGrad296(q.xy,qdx.xy,qdy.xy,17u,0),.55*detail);perturb+=float3(z.x,z.y,0)*w.z;}'),
        ('        SurfaceFrame296 fx=SurfaceFrameGrad296(q.zy,qdx.zy,qdy.zy,17u,0);\n        SurfaceFrame296 fy=SurfaceFrameGrad296(q.xz,qdx.xz,qdy.xz,17u,0);\n        SurfaceFrame296 fz=SurfaceFrameGrad296(q.xy,qdx.xy,qdy.xy,17u,0);\n        float3 rockMean=SAMPLE_TEXTURE2D_LOD(_RockMap,sampler_Surface296_linear_repeat_aniso8,float2(.5,.5),12).rgb;\n        rock=SurfaceColourMean296(TEXTURE2D_ARGS(_RockMap,sampler_Surface296_linear_repeat_aniso8),fx,rockMean)*w.x+\n            SurfaceColourMean296(TEXTURE2D_ARGS(_RockMap,sampler_Surface296_linear_repeat_aniso8),fy,rockMean)*w.y+\n            SurfaceColourMean296(TEXTURE2D_ARGS(_RockMap,sampler_Surface296_linear_repeat_aniso8),fz,rockMean)*w.z;\n        if(distanceWS<240)\n        {\n            fx=SurfaceFrameGrad296(q.zy,qdx.zy,qdy.zy,19u,0);\n            fy=SurfaceFrameGrad296(q.xz,qdx.xz,qdy.xz,19u,0);\n            fz=SurfaceFrameGrad296(q.xy,qdx.xy,qdy.xy,19u,0);\n            cavity=SurfaceData296(TEXTURE2D_ARGS(_StrataFracture276,sampler_Surface296_linear_repeat_aniso8),fx).g*w.x+\n                SurfaceData296(TEXTURE2D_ARGS(_StrataFracture276,sampler_Surface296_linear_repeat_aniso8),fy).g*w.y+\n                SurfaceData296(TEXTURE2D_ARGS(_StrataFracture276,sampler_Surface296_linear_repeat_aniso8),fz).g*w.z;\n        }',
         '        float3 rockMean=SAMPLE_TEXTURE2D_LOD(_RockMap,sampler_Surface296_linear_repeat_aniso8,float2(.5,.5),12).rgb;\n        // #307: a projection at or below _TriplanarSkip307 is not sampled (0 keeps every projection)\n        [branch] if(w.x>_TriplanarSkip307)rock+=SurfaceColourMean296(TEXTURE2D_ARGS(_RockMap,sampler_Surface296_linear_repeat_aniso8),SurfaceFrameGrad296(q.zy,qdx.zy,qdy.zy,17u,0),rockMean)*w.x;\n        [branch] if(w.y>_TriplanarSkip307)rock+=SurfaceColourMean296(TEXTURE2D_ARGS(_RockMap,sampler_Surface296_linear_repeat_aniso8),SurfaceFrameGrad296(q.xz,qdx.xz,qdy.xz,17u,0),rockMean)*w.y;\n        [branch] if(w.z>_TriplanarSkip307)rock+=SurfaceColourMean296(TEXTURE2D_ARGS(_RockMap,sampler_Surface296_linear_repeat_aniso8),SurfaceFrameGrad296(q.xy,qdx.xy,qdy.xy,17u,0),rockMean)*w.z;\n        // skipped weight is re-normalised onto the sampled projections (the result stays a weighted mean)\n        float keptWeight=(w.x>_TriplanarSkip307?w.x:0)+(w.y>_TriplanarSkip307?w.y:0)+(w.z>_TriplanarSkip307?w.z:0);\n        if(_TriplanarSkip307>0)rock/=max(keptWeight,1e-4);\n        if(distanceWS<240)\n        {\n            cavity=0;\n            [branch] if(w.x>_TriplanarSkip307)cavity+=SurfaceData296(TEXTURE2D_ARGS(_StrataFracture276,sampler_Surface296_linear_repeat_aniso8),SurfaceFrameGrad296(q.zy,qdx.zy,qdy.zy,19u,0)).g*w.x;\n            [branch] if(w.y>_TriplanarSkip307)cavity+=SurfaceData296(TEXTURE2D_ARGS(_StrataFracture276,sampler_Surface296_linear_repeat_aniso8),SurfaceFrameGrad296(q.xz,qdx.xz,qdy.xz,19u,0)).g*w.y;\n            [branch] if(w.z>_TriplanarSkip307)cavity+=SurfaceData296(TEXTURE2D_ARGS(_StrataFracture276,sampler_Surface296_linear_repeat_aniso8),SurfaceFrameGrad296(q.xy,qdx.xy,qdy.xy,19u,0)).g*w.z;\n            if(_TriplanarSkip307>0)cavity/=max(keptWeight,1e-4);\n        }'),
    ],
}


def apply(name, text):
    for old, new in PAIRS.get(name, []):
        if text.count(old) != 1: raise ValueError("#307 ground patch anchor not unique in " + name + ": " + old[:60])
        text = text.replace(old, new, 1)
    return text
