from pathlib import Path
import json, html
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'Art/World/WorldMacro/Compact/KcisaReplacement'
style='''*{box-sizing:border-box}body{margin:0;background:#161916;color:#e8e6dc;font:16px/1.7 "Malgun Gothic",sans-serif}main{max-width:1360px;margin:auto;padding:44px 28px}h1{font-size:34px}h2{margin-top:56px;font-size:24px}p{max-width:1050px}a{color:#bbd6c3}nav{display:flex;gap:22px;flex-wrap:wrap}.note{padding:18px 22px;border-left:3px solid #ba985d;background:#242820}img{width:100%;display:block}figure{margin:24px 0;border:1px solid #42463f}figcaption{padding:14px 20px;background:#222720}.grid{display:grid;grid-template-columns:1fr 1fr;gap:24px}.comparison{position:relative;aspect-ratio:16/9}.comparison img{position:absolute;inset:0;height:100%;object-fit:cover}.comparison .before{clip-path:inset(0 50% 0 0)}label{display:block;margin:12px 0}input[type=range]{width:100%;accent-color:#bbc8a9}table{border-collapse:collapse;width:100%;font-size:14px}th,td{text-align:left;border-bottom:1px solid #45473f;padding:13px}small{color:#bec3b5}.pending{color:#e6ba75}@media(max-width:800px){.grid{grid-template-columns:1fr}main{padding:22px 14px}h1{font-size:26px}}'''
ground='''<h2 id="ground">지면 채도 20%</h2><p>현재 축소 맵 전체의 흙길·지면·배경 지형·관청 마당: 재질 채도 <b>0.8 → 0.2</b>. 재질 3종 / 렌더러 97개에 적용했습니다. 식생·건물·물·전역 노출은 유지했습니다.</p><p><small>동일 카메라 · 1920×1080 · 정지 화면 비교. 왼쪽은 변경 전, 오른쪽은 변경 후입니다. 풀/나무 카드 준비 상태와 바람은 별도 렌더 시간의 영향을 받을 수 있습니다.</small></p><figure><div class="comparison"><img src="ground_after.png" alt="지면 채도 20%"><img class="before" id="before" src="ground_before.png" alt="변경 전 80%"></div><figcaption><label for="reveal">변경 전 ↔ 변경 후</label><input id="reveal" type="range" min="0" max="100" value="50" aria-label="전후 비교 위치"></figcaption></figure><p><a href="ground_before.png">변경 전 원본</a> · <a href="ground_after.png">변경 후 원본</a> · <a href="ground_saturation.json">적용값</a></p>'''
script='''<script>document.getElementById('reveal').addEventListener('input',e=>document.getElementById('before').style.clipPath=`inset(0 ${100-e.target.value}% 0 0)`);</script>'''
def page(title,body):return '<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+title+'</title><style>'+style+'</style><main>'+body+'</main>'+script+'</html>'
(OUT/'GROUND_REVIEW.html').write_text(page('오행부 — 지면 채도 20%', '<nav><a href="REVIEW.html">전체 교체 검토</a></nav><h1>지면 채도 20%</h1>'+ground),encoding='utf-8')
cards=[('house','KCISA 초가집','박스형 건물 61개를 보유 House_2 에셋의 공유 LOD 모델로 교체. 기존 승인 주막·관청·궁궐은 보존.'),
       ('clerk','인물 외형','캡슐 대신 기존 C02 인물 모델을 재사용. 플레이어 붓·1인칭 팔은 제거. 인물별 얼굴·직업 의상은 최종 제작 전의 공통 외형이다.'),
       ('beast','일반 적 외형','보유 호랑이·해태·사슴·거북이 계열을 재사용. 소환 전용 소멸 셰이더는 영구 표시 재질로 분리했다.'),
       ('pagoda','새 석탑과 KCISA 석재 바닥','석탑은 Blender 신규 메시 5,580 tris / 재질 1개. 바닥은 제주목 관아 석재 바닥 에셋. 기존 단의 지지 높이를 유지.'),
       ('shrine','돌무더기 성황당','임시 상자를 보유 바위 에셋 군집으로 교체. 휴식·체크포인트 기능은 기존 경로를 유지.'),
       ('tree','신목','원판을 쌓은 나무를 보유 느릅나무 모델로 교체. 기존 공유 LOD·바람 재질 사용. 주변 원경 카드의 품질은 별도 개선 대상.')]
figures=''.join('<figure><a href="'+key+'.png"><img loading="lazy" src="'+key+'.png" alt="'+title+'"></a><figcaption><b>'+title+'</b><br>'+desc+'</figcaption></figure>' for key,title,desc in cards)
body='''<small>오행부 / W_Demo_Compact / 2026-09-16</small><h1>에셋 교체와 지면 색 조정</h1><nav><a href="#ground">지면 전후</a><a href="#assets">교체 외형</a><a href="#mountain">원경 산 제안</a><a href="#checks">검사·남은 작업</a></nav><p class="note"><b>부분 완료 · 고유 보스 4개 외형 제작 대기</b><br>일반 건물·환경 소품·NPC·적을 교체한 씬이 저장되었습니다. 전체 외형 교체 완료나 실제 전투 검증 완료를 뜻하지 않습니다. 새 빌드는 만들지 않았습니다.</p>'''+ground+'''<h2 id="assets">교체 외형</h2><p>교체 기록: 건물 61 · 성벽 구간 120 · 석재/목재 지지 구조 647 · 인물/짐승 외형 98 · 자연물/증거/성황당/등/석탑 53. 구조 수는 완성 건물 수와 다릅니다. 원본 공급자 에셋 대신 파생 메시·재질과 씬 배치만 수정했습니다.</p><p><small>아래 일부 외형 캡처는 채도 변경 전 촬영분입니다. 최신 지면 색은 상단의 전후 비교를 확인하세요. 정지 화면이며 이동 성능의 증거로 사용하지 않습니다.</small></p><div class="grid">'''+figures+'''</div><h2 id="mountain">원경 산 — 적용 전 제안</h2><p><b>먼 산의 바위 무늬를 줄이고 큰 먹 덩어리와 겹친 능선으로 읽히게 한다.</b> 근경 지면은 유지하고, 거리가 멀어질수록 텍스처·노멀·잔 명암을 함께 줄입니다. 뒤 능선은 종이색에 가까워지고 골짜기와 산기슭은 옅어지는 방식입니다.</p><figure><img loading="lazy" src="mountain_reference.png" alt="사용자가 제공한 겹산 참고 이미지"><figcaption>사용자 제공 참고 이미지. 새로 렌더링한 결과가 아닙니다.</figcaption></figure><p>가늘고 뾰족한 봉우리는 별도 지형 작업이 필요합니다. 재질만으로 숨기거나 전역 노출을 변경하지 않습니다. <a href="MOUNTAIN_PROPOSAL.md">구체적인 방법과 TEST 거리</a></p><h2 id="checks">검사와 남은 작업</h2><table><tr><th>항목</th><th>확인한 범위</th></tr><tr><td>기존 씬 보존</td><td>기존 객체 삭제 0 · 기존 Transform 위치/회전/크기 변경 0 · 지형 콜라이더 88개 바인딩 유지. 기존 MonoBehaviour 변경은 적의 표시 렌더러 연결과 진단 계측값.</td></tr><tr><td>외형 참조</td><td>재질/셰이더 누락, 스킨 본 참조, 폐기된 렌더러 연결 검사. 자세한 현재 결과는 technical_checks.json.</td></tr><tr><td>석재 바닥</td><td>613개 상단 메시를 제주목 관아 석재 바닥으로 재연결. 석탑 앞 바닥의 실제 표시 확인. 모든 위치의 육안 검수는 아님.</td></tr><tr><td>통합 Play</td><td class="pending">미검증. 기존 지형 Terrain_050의 현재 콜라이더와 이전 경사/내비 기록 불일치로 검사 시작이 차단됨. 백업과 비교했을 때 해당 콜라이더는 이번 작업 전부터 같은 참조였음. 검사 가드를 해제하지 않음.</td></tr><tr><td>고유 외형</td><td class="pending">청룡 · 주작 · 이무기 · 메카천수관음은 미완료. 앞의 3종은 Meshy 잔액 부족으로 생성 시작 전 중단, 사용 크레딧 0. 천수관음은 보유 KCISA 관음상 기반의 기계 장치 각색이 남음.</td></tr><tr><td>성능·전투·통행</td><td class="pending">이동 중 프레임타임, 새 건물 출입·내비 재검증, 외형과 공격 애니메이션의 실제 동기화는 미검증.</td></tr></table><p><a href="replacements.json">출처와 교체 원장</a> · <a href="preservation_checks.json">씬 보존 대조</a> · <a href="technical_checks.json">외형 기술 검사</a> · <a href="animation_bindings.json">애니메이션 경로 검사</a> · <a href="REPORT.md">기술 기록</a></p>'''
(OUT/'REVIEW.html').write_text(page('오행부 — KCISA 교체 검토',body),encoding='utf-8')
print(OUT/'GROUND_REVIEW.html')
