"""One-shot authoring migration for 누; do not rerun on modified sources."""
from pathlib import Path
import hashlib,json
r=Path('Oheangbu/Assets/_Project/Scripts');e=r/'Editor/SpellVFX120';o=Path('Art/SpellVFX120')
(o/'nu66_before_profiles.json').write_text(json.dumps({p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in Path('Oheangbu/Assets/_Project/Art/SpellVFX120/Profiles').glob('*.asset')}))
p=r/'App/SpellVFX120/Vfx120Effect.FireAura.cs';s=p.read_text(encoding='utf-8');s=s.replace('public static bool IsFireAura(', 'public static bool IsFireWard(Vfx120Profile p)=>p!=null&&p.Glyph=="누"&&p.NativeBodyPrefab!=null&&p.NativeBodyPrefab.name=="PF_FireWard_043";\n  public static bool IsFireAura(').replace('=>IsFireSteam(p)||','=>IsFireWard(p)||IsFireSteam(p)||').replace('IsFireMelt(Profile)||IsFireSteam(Profile))','IsFireMelt(Profile)||IsFireSteam(Profile)||IsFireWard(Profile))');p.write_text(s,encoding='utf-8')
s=(e/'Vfx120FireAuraBuilder.cs').read_text(encoding='utf-8').replace('Vfx120FireAuraBuilder','Vfx120FireWardBuilder').replace('032_B109','043_B204').replace('PF_FireAura_032','PF_FireWard_043').replace('fire_aura_032','fire_ward_043').replace('glyph="넉"','glyph="누"').replace('p.Duration=3.2f','p.Duration=4f').replace('(.6f,1.1f)','(1.5f,2.1f)').replace('(.4f,.6f)','(.7f,1f)').replace('(.18f,.34f)','(.3f,.5f)').replace('Circular flame field plus confirmed hit motif. Latest-contact feedback slot reused; gameplay DOT not added.','Stationary fire curtain and floor seal; contact feedback only, no parry or mitigation rules.').replace('if(e.FireAuraContacts!=2','if(Vfx120Effect.IsFireGuard(p))throw new Exception("Ward incorrectly classified as parry");if(e.FireAuraContacts!=2')
(e/'Vfx120FireWardBuilder.cs').write_text(s,encoding='utf-8')
p=e/'Vfx120Queue.cs';s=p.read_text(encoding='utf-8').replace('case "FireAuraBuild":','case "FireWardBuild": response.result=Vfx120FireWardBuilder.Build(); break;\n                    case "FireAuraBuild":');p.write_text(s,encoding='utf-8')
p=e/'Vfx120TraditionalPlayAudit.cs';s=p.read_text(encoding='utf-8').replace('&&row.glyph!="농")','&&row.glyph!="농"&&row.glyph!="누")');p.write_text(s,encoding='utf-8')
