"""One-shot 눈 authoring migration; source snapshots must be preserved before reuse."""
from pathlib import Path
import json,hashlib
r=Path('Oheangbu/Assets/_Project/Scripts');e=r/'Editor/SpellVFX120';o=Path('Art/SpellVFX120')
(o/'nun67_before_profiles.json').write_text(json.dumps({p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in Path('Oheangbu/Assets/_Project/Art/SpellVFX120/Profiles').glob('*.asset')}))
p=r/'App/SpellVFX120/Vfx120Effect.FireAura.cs';s=p.read_text(encoding='utf-8').replace('public static bool IsFireAura(','''public static bool IsFireBurn(Vfx120Profile p)=>p!=null&&p.Glyph=="눈"&&p.NativeBodyPrefab!=null&&p.NativeBodyPrefab.name=="PF_FireBurn_045";
  Vector3 _burnFrom,_burnTo;float _burnAt=-1;
  public float FireBurnProgress=>_burnAt<0?0:Mathf.Clamp01((Age-_burnAt)/1.8f);
  public bool BeginFireBurnPath(Vector3 from,Vector3 to){if(!IsFireBurn(Profile)||!FireAuraConfigured||_burnAt>=0||Age>Life-2.4f||!Vfx120InterceptionMotion.Finite(from)||!Vfx120InterceptionMotion.Finite(to)||(to-from).sqrMagnitude<.0001f)return false;_burnFrom=from;_burnTo=to;_burnAt=Age;return true;}
  public static bool IsFireAura(''').replace('=>IsFireWard(p)||','=>IsFireBurn(p)||IsFireWard(p)||')
s=s.replace('if(IsFireBackblast(Profile))_auraMark', 'if(IsFireBurn(Profile)){_auraSeal.transform.localPosition=Vector3.zero;_auraSeal.transform.localRotation=Quaternion.identity;_auraSeal.transform.localScale=Vector3.one*.6f;}\n   if(IsFireBackblast(Profile))_auraMark')
s=s.replace('if(IsFireJet(Profile)){Vector3 d=', '''if(IsFireBurn(Profile)){if(PreviewControlled&&DemonstrationCues&&_burnAt<0)BeginFireBurnPath(ReceivedOrigin,TargetPoint());if(_burnAt>=0){_fireAura.transform.position=Vector3.Lerp(_burnFrom,_burnTo,FireBurnProgress);if(FireBurnProgress>=1&&FireAuraContacts==0)SignalFireAuraHit(_burnTo);}}
   else if(IsFireJet(Profile)){Vector3 d=''')
s=s.replace('p.Simulate(dt,false,false,false);}', 'if(IsFireBurn(Profile))em.enabled=_burnAt>=0&&at<_burnAt+1.8f;p.Simulate(dt,false,false,false);}')
s=s.replace('(IsFireSword(Profile)||IsFireJet(Profile))&&','(IsFireSword(Profile)||IsFireJet(Profile)||IsFireBurn(Profile))&&')
s=s.replace('_empowerConsumedAt=-1;_healingAt=-1;', '_empowerConsumedAt=-1;_burnAt=-1;_healingAt=-1;')
s=s.replace('float sealFade=fade*','float sealFade=(IsFireBurn(Profile)?(_burnAt<0?0:1-FireBurnProgress):1)*fade*')
p.write_text(s,encoding='utf-8')
s=(e/'Vfx120FireAuraBuilder.cs').read_text(encoding='utf-8').replace('Vfx120FireAuraBuilder','Vfx120FireBurnBuilder').replace('032_B109','045_B208').replace('PF_FireAura_032','PF_FireBurn_045').replace('fire_aura_032','fire_burn_045').replace('glyph="넉"','glyph="눈"').replace('p.Duration=3.2f','p.Duration=3.4f').replace('shape.radius=1.5f','shape.radius=.12f').replace('shape.radiusThickness=.12f','shape.radiusThickness=1f').replace('new Vector3(0,-.78f,0)','Vector3.zero').replace('Circular flame field plus confirmed hit motif. Latest-contact feedback slot reused; gameplay DOT not added.','Noncombat burn-front VFX follows a supplied segment; no environment destruction or damage.').replace('e.Sample(.3f);','e.Sample(.1f);if(e.FireAuraParticles!=0)throw new Exception("Unrequested burn");if(!e.BeginFireBurnPath(Vector3.up,new Vector3(0,1,4))||e.BeginFireBurnPath(Vector3.up,Vector3.forward))throw new Exception("Burn path single-start");e.Sample(.3f);').replace('e.SignalFireAuraHit(new Vector3(1,1,0));e.Sample(.32f);if(e.FireAuraMarkOpacity<.8f)throw new Exception("No hit mark");e.Sample(1);e.SignalFireAuraHit(new Vector3(-1,1,0));e.Sample(1.02f);if(e.FireAuraContacts!=2||e.FireAuraMarkOpacity<.8f)throw new Exception("Repeat contact failed");','e.Sample(1.92f);if(e.FireBurnProgress<1||e.FireAuraContacts!=1||e.FireAuraMarkOpacity<.8f)throw new Exception("Burn completion missing");').replace('PASS_RING_REPEATED_CONTACT_MARK_AND_CLEANUP','PASS_EXPLICIT_PATH_PROGRESS_COMPLETION_CLEANUP')
(e/'Vfx120FireBurnBuilder.cs').write_text(s,encoding='utf-8')
p=e/'Vfx120Queue.cs';s=p.read_text(encoding='utf-8').replace('case "FireAuraBuild":','case "FireBurnBuild": response.result=Vfx120FireBurnBuilder.Build(); break;\n                    case "FireAuraBuild":');p.write_text(s,encoding='utf-8')
p=e/'Vfx120TraditionalPlayAudit.cs';s=p.read_text(encoding='utf-8').replace('public bool steamOnlySeen;','public bool steamOnlySeen;\n            public float fireBurnProgress;').replace('{ if(Vfx120Effect.IsFireJet(t.effect.Profile))','{ if(Vfx120Effect.IsFireBurn(t.effect.Profile)){t.effect.BeginFireBurnPath(t.effect.transform.position,t.effect.transform.position+Vector3.forward*3);row.fireBurnProgress=Mathf.Max(row.fireBurnProgress,t.effect.FireBurnProgress);}else if(Vfx120Effect.IsFireJet(t.effect.Profile))').replace('&& (row.glyph!="농"','&& (row.glyph!="눈"||row.fireBurnProgress>=1)\n                && (row.glyph!="농"').replace('&&row.glyph!="논")','&&row.glyph!="논"&&row.glyph!="눈")')
# Final sequential regression has its own output, preserving per-version capture evidence.
s=s.replace('public static string Start() =>', 'public static string StartNieun() => StartRun(false,false,null,true);\n        public static string Start() =>').replace('string singleGlyph = null)','string singleGlyph = null, bool nieun = false)').replace('Owned.Clear(); Assets.Clear(); _current = null;', '''if(nieun){_report.glyphs=new[]{"나","낙","난","남","낫","낭","너","넉","넌","넘","넛","넝","노","녹","논","놈","놋","농","누","눈"};_report.output=Path.Combine(Vfx120Editor.Output,"nieun_final_play_audit.json");_report.scope="Twenty assigned nieun effects sequentially in latest runtime; synthetic presentation signals, no art/gameplay/performance approval.";}
            Owned.Clear(); Assets.Clear(); _current = null;''')
p.write_text(s,encoding='utf-8')
p=e/'Vfx120Queue.cs';s=p.read_text(encoding='utf-8').replace('case "SinglePlayAudit":','case "NieunPlayAudit": response.result=Vfx120TraditionalPlayAudit.StartNieun(); break;\n                    case "SinglePlayAudit":');p.write_text(s,encoding='utf-8')
